package com.PocketIdentityDirectory.users.models.helpers;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Country {
    @JsonEnumDefaultValue
    @JsonProperty("")
    NULL,
    @JsonProperty("Afghanistan") AF,
    @JsonProperty("Åland Islands") AX,
    @JsonProperty("Albania") AL,
    @JsonProperty("Algeria") DZ,
    @JsonProperty("America") AS,
    @JsonProperty("American Minor Outlying Islands") UM,
    @JsonProperty("American Virgin Islands") VI,
    @JsonProperty("Andorra") AD,
    @JsonProperty("Angola") AO,
    @JsonProperty("Anguilla") AI,
    @JsonProperty("Antarctica") AQ,
    @JsonProperty("Antigua and Barbuda") AG,
    @JsonProperty("Argentina") AR,
    @JsonProperty("Armenia") AM,
    @JsonProperty("Aruba") AW,
    @JsonProperty("Australia") AU,
    @JsonProperty("Austria") AT,
    @JsonProperty("Azerbaijan") AZ,
    @JsonProperty("Bahamas") BS,
    @JsonProperty("Bahrain") BH,
    @JsonProperty("Bangladesh") BD,
    @JsonProperty("Barbados") BB,
    @JsonProperty("Belarus") BY,
    @JsonProperty("Belgium") BE,
    @JsonProperty("Belize") BZ,
    @JsonProperty("Benin") BJ,
    @JsonProperty("Bermuda") BM,
    @JsonProperty("Bhutan") BT,
    @JsonProperty("Bolivia") BO,
    @JsonProperty("Bosnia and Herzegovina") BA,
    @JsonProperty("Botswana") BW,
    @JsonProperty("Bouvet Island") BV,
    @JsonProperty("Brazil") BR,
    @JsonProperty("British Indian Ocean Territory") IO,
    @JsonProperty("British Virgin Islands") VG,
    @JsonProperty("Brunei") BN,
    @JsonProperty("Bulgaria") BG,
    @JsonProperty("Burkina Faso") BF,
    @JsonProperty("Burundi") BI,
    @JsonProperty("Cambodia") KH,
    @JsonProperty("Cameroon") CM,
    @JsonProperty("Canada") CA,
    @JsonProperty("Cape Verde") CV,
    @JsonProperty("Cayman Islands") KY,
    @JsonProperty("Central African Republic") CF,
    @JsonProperty("Chad") TD,
    @JsonProperty("Chile") CL,
    @JsonProperty("China") CN,
    @JsonProperty("Christmas Island") CX,
    @JsonProperty("Cocos Islands") CC,
    @JsonProperty("Colombia") CO,
    @JsonProperty("Comoros") KM,
    @JsonProperty("Congo") CG,
    @JsonProperty("Cook Islands") CK,
    @JsonProperty("Costa Rica") CR,
    @JsonProperty("Croatia") HR,
    @JsonProperty("Cuba") CU,
    @JsonProperty("Cyprus") CY,
    @JsonProperty("Czech Republic") CZ,
    @JsonProperty("Denmark") DK,
    @JsonProperty("Djibouti") DJ,
    @JsonProperty("Dominica") DM,
    @JsonProperty("Dominican Republic") DO,
    @JsonProperty("Ecuador") EC,
    @JsonProperty("Egypt") EG,
    @JsonProperty("El Salvador") SV,
    @JsonProperty("Equatorial Guinea") GQ,
    @JsonProperty("Eritrea") ER,
    @JsonProperty("Estonia") EE,
    @JsonProperty("Ethiopia") ET,
    @JsonProperty("Falkland Islands") FK,
    @JsonProperty("Faroe Islands") FO,
    @JsonProperty("Fiji") FJ,
    @JsonProperty("Finland") FI,
    @JsonProperty("France") FR,
    @JsonProperty("French Guiana") GF,
    @JsonProperty("French Polynesia") PF,
    @JsonProperty("French Southern Territories") TF,
    @JsonProperty("Gabon") GA,
    @JsonProperty("Gambia") GM,
    @JsonProperty("Georgia") GE,
    @JsonProperty("Germany") DE,
    @JsonProperty("Ghana") GH,
    @JsonProperty("Gibraltar") GI,
    @JsonProperty("Greece") GR,
    @JsonProperty("Greenland") GL,
    @JsonProperty("Grenada") GD,
    @JsonProperty("Guadeloupe") GP,
    @JsonProperty("Guam") GU,
    @JsonProperty("Guatemala") GT,
    @JsonProperty("Guernsey") GG,
    @JsonProperty("Guinea") GN,
    @JsonProperty("Guinea-Bissau") GW,
    @JsonProperty("Guyana") GY,
    @JsonProperty("Haiti") HT,
    @JsonProperty("Heard Island and McDonald Islands") HM,
    @JsonProperty("Honduras") HN,
    @JsonProperty("Hong Kong") HK,
    @JsonProperty("Hungary") HU,
    @JsonProperty("Iceland") IS,
    @JsonProperty("India") IN,
    @JsonProperty("Indonesia") ID,
    @JsonProperty("Iran") IR,
    @JsonProperty("Iraq") IQ,
    @JsonProperty("Ireland") IE,
    @JsonProperty("Isle of Man") IM,
    @JsonProperty("Israel") IL,
    @JsonProperty("Italy") IT,
    @JsonProperty("Ivory Coast") CI,
    @JsonProperty("Jamaica") JM,
    @JsonProperty("Japan") JP,
    @JsonProperty("Jersey") JE,
    @JsonProperty("Jordan") JO,
    @JsonProperty("Kazakhstan") KZ,
    @JsonProperty("Kenya") KE,
    @JsonProperty("Kiribati") KI,
    @JsonProperty("Kuwait") KW,
    @JsonProperty("Kyrgyzstan") KG,
    @JsonProperty("Laos") LA,
    @JsonProperty("Latvia") LV,
    @JsonProperty("Lebanon") LB,
    @JsonProperty("Lesotho") LS,
    @JsonProperty("Liberia") LR,
    @JsonProperty("Libya") LY,
    @JsonProperty("Liechtenstein") LI,
    @JsonProperty("Lithuania") LT,
    @JsonProperty("Luxembourg") LU,
    @JsonProperty("Macau") MO,
    @JsonProperty("Madagascar") MG,
    @JsonProperty("Malawi") MW,
    @JsonProperty("Malaysia") MY,
    @JsonProperty("Maldives") MV,
    @JsonProperty("Mali") ML,
    @JsonProperty("Malta") MT,
    @JsonProperty("Marshall Islands") MH,
    @JsonProperty("Martinique") MQ,
    @JsonProperty("Mauritania") MR,
    @JsonProperty("Mauritius") MU,
    @JsonProperty("Mayotte") YT,
    @JsonProperty("Mexico") MX,
    @JsonProperty("Micronesia") FM,
    @JsonProperty("Moldova") MD,
    @JsonProperty("Monaco") MC,
    @JsonProperty("Mongolia") MN,
    @JsonProperty("Montenegro") ME,
    @JsonProperty("Montserrat") MS,
    @JsonProperty("Morocco") MA,
    @JsonProperty("Mozambique") MZ,
    @JsonProperty("Myanmar") MM,
    @JsonProperty("Namibia") NA,
    @JsonProperty("Nauru") NR,
    @JsonProperty("Nepal") NP,
    @JsonProperty("Netherlands") NL,
    @JsonProperty("New Caledonia") NC,
    @JsonProperty("New Zealand") NZ,
    @JsonProperty("Nicaragua") NI,
    @JsonProperty("Niger") NE,
    @JsonProperty("Nigeria") NG,
    @JsonProperty("Niue") NU,
    @JsonProperty("Norfolk Island") NF,
    @JsonProperty("North Korea") KP,
    @JsonProperty("North Macedonia") MK,
    @JsonProperty("Northern Mariana Islands") MP,
    @JsonProperty("Norway") NO,
    @JsonProperty("Oman") OM,
    @JsonProperty("Pakistan") PK,
    @JsonProperty("Palau") PW,
    @JsonProperty("Palestine") PS,
    @JsonProperty("Panama") PA,
    @JsonProperty("Papua New Guinea") PG,
    @JsonProperty("Paraguay") PY,
    @JsonProperty("Peru") PE,
    @JsonProperty("Philippines") PH,
    @JsonProperty("Pitcairn") PN,
    @JsonProperty("Poland") PL,
    @JsonProperty("Portugal") PT,
    @JsonProperty("Puerto Rico") PR,
    @JsonProperty("Qatar") QA,
    @JsonProperty("Reunion") RE,
    @JsonProperty("Romania") RO,
    @JsonProperty("Russia") RU,
    @JsonProperty("Rwanda") RW,
    @JsonProperty("Saint Helena") SH,
    @JsonProperty("Saint Kitts and Nevis") KN,
    @JsonProperty("Saint Lucia") LC,
    @JsonProperty("Saint Pierre and Miquelon") PM,
    @JsonProperty("Saint Vincent and the Grenadines") VC,
    @JsonProperty("Samoa") WS,
    @JsonProperty("San Marino") SM,
    @JsonProperty("Saudi Arabia") SA,
    @JsonProperty("Senegal") SN,
    @JsonProperty("Serbia") RS,
    @JsonProperty("Seychelles") SC,
    @JsonProperty("Sierra Leone") SL,
    @JsonProperty("Singapore") SG,
    @JsonProperty("Slovakia") SK,
    @JsonProperty("Slovenia") SI,
    @JsonProperty("Solomon Islands") SB,
    @JsonProperty("Somalia") SO,
    @JsonProperty("South Africa") ZA,
    @JsonProperty("South Georgia and the South Sandwich Islands") GS,
    @JsonProperty("South Korea") KR,
    @JsonProperty("Spain") ES,
    @JsonProperty("Sri Lanka") LK,
    @JsonProperty("Sudan") SD,
    @JsonProperty("Suriname") SR,
    @JsonProperty("Svalbard and Jan Mayen") SJ,
    @JsonProperty("Sweden") SE,
    @JsonProperty("Switzerland") CH,
    @JsonProperty("Syria") SY,
    @JsonProperty("Taiwan") TW,
    @JsonProperty("Tajikistan") TJ,
    @JsonProperty("Tanzania") TZ,
    @JsonProperty("Thailand") TH,
    @JsonProperty("Timor-Leste") TL,
    @JsonProperty("Togo") TG,
    @JsonProperty("Tokelau") TK,
    @JsonProperty("Tonga") TO,
    @JsonProperty("Trinidad and Tobago") TT,
    @JsonProperty("Tunisia") TN,
    @JsonProperty("Turkey") TR,
    @JsonProperty("Turkmenistan") TM,
    @JsonProperty("Turks and Caicos Islands") TC,
    @JsonProperty("Tuvalu") TV,
    @JsonProperty("Uganda") UG,
    @JsonProperty("Ukraine") UA,
    @JsonProperty("United Arab Emirates") AE,
    @JsonProperty("United Kingdom") GB,
    @JsonProperty("United States") US,
    @JsonProperty("Uruguay") UY,
    @JsonProperty("Uzbekistan") UZ,
    @JsonProperty("Vanuatu") VU,
    @JsonProperty("Vatican City") VA,
    @JsonProperty("Venezuela") VE,
    @JsonProperty("Vietnam") VN,
    @JsonProperty("Wallis and Futuna") WF,
    @JsonProperty("Western Sahara") EH,
    @JsonProperty("Yemen") YE,
    @JsonProperty("Zambia") ZM,
    @JsonProperty("Zimbabwe") ZW;

}
